---
# tasks file for nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy index.html to Nginx directory
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

